### ISSUE TITLE
Plugin doesn't work in Contao 4.8

### ISSUE THREAD

**Issue by leonexcc** [postyou/contao-abr-streaming-bundle#4]
Since mediaelement.js was removed here: https://github.com/contao/contao/commit/1b5fb884bb97e9ab3416bed1766db00425cbeca4, this plugin will not work anymore in new Contao versions.

**Comment by MarkejN** [comment]
Did you use the latest release? This should install mediaelement as a required package.

**Comment by leonexcc** [comment]
I think this was released shortly after i opened this issue. I will test it as soon as possible.

**Comment by leonexcc** [comment]
It works now! :-)
